{{- $app := .Values.apps.admin -}}
{{- $deployment := $app.deployments.nginx -}}
{{- $resourceName := printf "%s-%s" $app.name $deployment.name }}
{{- $linkedResourceName := printf "%s-%s" $app.name $app.deployments.fpm.name }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $resourceName }}
  labels:
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    app: {{ $app.name }}
    role: {{ $deployment.name }}
data:
  k8s-auth.conf: |
      server {
        server_name {{ $app.ingress.hostname }};
        listen {{ $deployment.port }} default_server;
        root /app/public;
        location = /_healthz {
          add_header Content-Type text/plain;
          return 200 'ok';
        }
        location / {
          index index.php;
          try_files $uri /index.php?q=$uri&$args;
        }
        location ~ \.php$ {
          fastcgi_index  index.php;
          include fastcgi_params;
          fastcgi_param REQUEST_METHOD $request_method;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_pass {{ $linkedResourceName }}:{{ $app.deployments.fpm.service.port }};
        }
      }
