# Default values for p1-auth.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount:
  nginx: 2
  fpm: 2

enableRedis: false
enableMongo: false
enableCertIssuer: false

images:
  nginx: "nginx:1.15.4"
  fpm-auth: "p1hub/p1-dev.php-fpm:latest"
  
apps:
  auth:
    name: p1auth
    ingress:
      hostname: auth-tst.protocol.one
      path: /
    deployments:
      nginx:
        name: nginx
        image: "nginx:1.15.4"
        port: 80
        replicas: 2
        service: 
          name: nginx
          type: ClusterIP
          port: 8080
          protocol: TCP
        configMap: 
          mountPath: /etc/nginx/conf.d/
      fpm:
        name: fpm
        image: "p1hub/auth.protocol.one:1.0.0"
        port: 9000
        replicas: 2
        service:
          name: fpm
          type: ClusterIP
          port: 9000
          protocol: TCP
              
    
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
