{{- $app := .Values.apps.api -}}
{{- $deployment := $app.deployments.fpm -}}
{{- $resourceName := printf "%s-%s" $app.name $deployment.name }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $resourceName }}
  labels:
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    app: {{ $app.name }}
    role: {{ $deployment.name }}
  annotations: 
    released: {{ .Release.Time}}    
spec:
  selector:
    matchLabels:
      chart: {{ .Chart.Name }}
      release: {{ .Release.Name }}
      app: {{ $app.name }}
      role: {{ $deployment.name }}
  replicas: {{ $deployment.replicas }} 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        chart: {{ .Chart.Name }}
        release: {{ .Release.Name }}
        app: {{ $app.name }}
        role: {{ $deployment.name }}
    annotations:
      released: {{ .Release.Time}}
    spec:
      {{- if $deployment.configMap }}
      volumes:
      - name: {{ $resourceName }}
        configMap:
          name: {{ $resourceName }}
      {{- end }}
      containers:
      - name: {{ $resourceName }}
        image: {{ $deployment.image }}
        env:
          - name: S3_BUCKET_NAME
            valueFrom:
              secretKeyRef:
                name: p1admin-s3
                key: s3_bucket_name
          - name: S3_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: p1admin-s3
                key: s3_secret_key
          - name: S3_REGION
            valueFrom:
              secretKeyRef:
                name: p1admin-s3
                key: s3_region
          - name: S3_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: p1admin-s3
                key: s3_access_key
          - name: S3_VERSION
            valueFrom:
              secretKeyRef:
                name: p1admin-s3
                key: s3_version
          - name: S3_SDK_VERSION
            valueFrom:
              secretKeyRef:
                name: p1admin-s3
                key: s3_sdk_version
        ports:
        - containerPort: {{ $deployment.port }}
        {{- if $deployment.configMap }}
        volumeMounts:
        - name: {{ $resourceName }}
          mountPath: {{ $deployment.configMap.mountPath }}
          readOnly: true
        {{- end }}