{{- if .Values.enableMongo }}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: p1auth-mongo
  labels:
    app: auth
    role: mongo
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 172.29.13.72
    path: "/k8sdata/p1auth-mongo"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: p1auth-mongo
spec:
  storageClassName: ""
  selector:
    matchLabels:
      app: "auth"  
      role: "mongo"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: p1-auth-mongo
  labels:
    app: auth
    role: mongo
spec:
  ports:
  - port: 27017
    protocol: TCP
  selector:
    app: auth
    role: mongo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: p1auth-mongo
spec:
  selector:
    matchLabels:
      app: auth
      role: mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: auth
        role: mongo
    spec:
      volumes:
      - name: p1auth-mongo
        persistentVolumeClaim:
          claimName: p1auth-mongo
      containers:
      - name: mongo
        image: library/mongo:4.1.3
#        env:
#        - name: MONGO_INITDB_ROOT_USERNAME
#          value: root
#        - name: MONGO_INITDB_ROOT_PASSWORD
#          value: example
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: p1auth-mongo
          mountPath: /data/db
          readOnly: false
{{- end }}